spring:
 application:
    name: holidays-api
 mcv:
     pathmatch:
       matching-strategy: ant_path_matcher
 h2:
    console:
      enabled: false
      path: /h2-console
server:
  port: ${APPLICATION_PORT:80}
loader:
  source: ${LOADER_SOURCE}
  remoteURL: ${LOADER_REMOTE_URL}
  branch: ${LOADER_BRANCH}
  filePath: ${LOADER_FILE_PATH}
  authToken: ${LOADER_AUTH_TOKEN}