spring:
 application:
    name: holidays-api
 mcv:
     pathmatch:
       matching-strategy: ant_path_matcher
 h2:
    console:
      enabled: false
      path: /h2-console
server:
  port: ${SERVER_PORT:80}
  error:
    include-stacktrace: never
loader:
  source: ${LOADER_SOURCE}
  remoteURL: ${LOADER_REMOTE_URL}
  branch: ${LOADER_BRANCH}
  filePath: ${LOADER_FILE_PATH}
  authToken: ${LOADER_AUTH_TOKEN}
rateLimit:
  globalBucket:
   id: ${RATE_LIMIT_GLOBAL_BUCKET_ID:global}
   capacity: ${RATE_LIMIT_GLOBAL_BUCKET_CAPACITY:500}
